{
    "openapi": "3.0.0",
    "info": {
        "title": "API Financeira",
        "description": "Essa API fornece serviços bancários, como por exemplo, transferências bancárias.",
        "termsOfService": "https://localhost:3333/terms",
        "contact": {
            "email": "gabriel.ilton@liveonsolutions.com"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:3333",
            "description": "API de test"
        }
    ],
    "paths": {
        "/create": {
            "post": {
                "summary": "Cadastro de conta.",
                "description": "Essa rota cria uma conta com nome, CPF, email, senha, endereço e telefone.",
                "tags": ["Account"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Account"
                            },
                            "examples": {
                                "account": {
                                    "value": {
                                        "name": "Anjo",
                                        "cpf": 10000000000,
                                        "email": "anjo@gmail.com",
                                        "password": "1000",
                                        "endereco": {
                                            "rua": "Bornoia",
                                            "bairro": "Comyto",
                                            "numero": 63
                                        },
                                        "telefone": 14999999999
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "400": {
                        "description": "Falha ao criar a conta."
                    },
                    "201": {
                        "description": "Sucesso ao criar a conta.",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "account": {
                                        "value": {
                                            "name": "Nome do usuário",
                                            "email": "Email do usuario"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },

        "/login": {
            "post": {
                "tags": ["Account"],
                "summary": "Realiza o login da conta já criada no banco.",
                "description": "Realiza o login na conta com email e senha que existe já foi criada na rota '/create' e gera um token que irá conter o Id da conta logada, seu secret e o tempo de expiração, com esse token é possível acessar as rotas e se autenticar.",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Login"
                            },
                            "examples": {
                                "login": {
                                    "value": {
                                        "email": "anjo@gmail.com",
                                        "password": "1000"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "404":{
                        "description": "Falha ao realizar o login."
                    },
                    "200": {
                        "description": "Sucesso ao logar.",
                        "content": {
                            "application/json": {
                                "examples":{
                                    "login": {
                                        "value": {
                                            "name": "Nome da conta que foi logada/acessada.",
                                            "token": "Retorna o token que será utilizado nas rotas para autenticação."
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }        
        },

        "/details": {
            "get": {
                "tags": ["Account"],
                "summary": "Busca os detalhes da conta.",
                "description": "Busca os detalhes de uma única conta cadastrada no banco referente ao Id do token.",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "404":{
                        "description": "Falha ao resgatar detalhes da conta."
                    },
                    "200": {
                        "description": "Sucesso ao resgatar os detalhes da conta",
                        "content": {
                            "application/json": {
                                "examples":{
                                    "details": {
                                        "value": {
                                            "name": "Retorna o nome da conta salva no banco.",
                                            "cpf": "Retorna o CPF da conta.",
                                            "email": "Retorna o email da conta.",
                                            "endereco": {
                                                "rua": "Retorna a rua cadastrada no endereco da conta.",
                                                "bairro": "Retorna o bairro cadastrado no endereco da conta.",
                                                "numero": "Retorna o numero cadastrado no endereco da conta."                                            },
                                            "telefone": "Retorna o telefone da conta salva no banco.",
                                            "admin": "Retorna o status de admin da conta se é verdadeiro ou falso."
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },

        "/balance": {
            "get": {
                "tags": ["Account"],
                "summary": "Recupera o saldo da conta.",
                "description": "Recupera o saldo da conta pelo Id contido no token do Headers.",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "404":{
                        "description": "Falha ao recuperar o saldo da conta."
                    },
                    "200": {
                        "description": "Sucesso ao recuperar o saldo da conta.",
                        "content": {
                            "application/json": {
                                "examples":{
                                    "balance": {
                                        "value": {
                                            "name": "Nome da conta que está sendo recuperado o saldo.",
                                            "saldo": "Retorna o saldo da conta."
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },

        "/accounts/list": {
            "get": {
                "tags": ["Account"],
                "summary": "Busca todas as contas.",
                "description": "Busca todas as contas cadastradas no banco e apenas administradores têm acesso a essa rota.",
                "security":[
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "404":{
                        "description": "Falha ao resgatar as contas."
                    },
                    "200": {
                        "description": "Sucesso ao recuperar as contas.",
                        "content": {
                            "application/json": {
                                "examples":{
                                    "accountsList": {
                                        "value": {
                                            "account": "Retorna todos os dados de cada conta."
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },

        "/password": {
            "put":{
                "summary": "Atualiza a senha da conta.",
                "description": "Atualiza a senha da conta que exista, a conta que será atualizada vem no token, pega o Id do token no Headers, a senha antiga, o email, e a senha nova do body e atualiza.",
                "tags": ["Account"],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Password"
                            },
                            "examples": {
                                "updatePassword": {
                                    "value": {
                                        "passwordOld": "1000",
                                        "email": "anjo@gmail.com",
                                        "passwordNew": "1100"
                                    }
                                }
                            }
                        }
                    }  
                },
                "responses": {
                    "400": {
                        "description": "Não foi possível alterar senha."
                    },
                    "201": {
                        "description": "Sucesso ao alterar senha da conta.",
                        "content": {
                            "application/json": {
                                "examples":{
                                    "updatePassword": {
                                        "value": {
                                            "nome":"Nome do usuario que teve a senha alterada.",
                                            "message": "Senha alterada com sucesso."
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },

        "/delete": {
            "delete": {
                "tags": ["Account"],
                "summary": "Deleta a conta.",
                "description": "Deleta a conta cadastrada de acordo com o Id recebido no token.",
                "security": [
                    {
                        "bearerAuth": [] 
                    }
                ],
                "responses": {
                    "404":{
                        "description": "Falha ao deletar a conta."
                    },
                    "200": {
                        "description": "Sucesso ao deletar a conta",
                        "content": {
                            "application/json": {
                                "examples":{
                                    "delete": {
                                        "value": {
                                            "deleted": "Retorna o nome da conta deletada.",
                                            "message": "Retorna a informação de deletado com sucesso."
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },

        "/retrieve": {  
            "put":{
                "summary": "Recupera a conta deleteda.",
                "description": "Recupera a conta que foi deletada recebendo no corpo da requisição o CPF da conta que deseja ser recuperada.",
                "tags": ["Account"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Retrieve"
                            },
                            "examples": {
                                "retrieve": {
                                    "value": {
                                        "cpf": 10000000000
                                    }
                                }
                            }
                        }
                    }  
                },
                "responses": {
                    "400": {
                        "description": "Conta não encontrada ou conta já existe."
                    },
                    "201": {
                        "description": "Sucesso ao recuperar a conta.",
                        "content": {
                            "application/json": {
                                "examples":{
                                    "retrieve": {
                                        "value": {
                                            "name":"Nome da conta que foi resgatada.",
                                            "message":"Mensagem com a informação de sucesso."
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },

        "/image": {
            "post": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "tags": ["Image"],
                "summary": "Faz o Upload da imagem.",
                "description": "Realiza o upload da imagem no banco levando o Id da conta logada.",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "file",
                                "in": "formData",
                                "format": "binary"
                            }
                        }
                    }
                },
                "responses": {
                    "404":{
                        "description": "Falha ao realizar o upload."
                    },
                    "200": {
                        "description": "Sucesso no upload.",
                        "content": {
                            "application/json": {
                                "examples":{
                                    "UploadImage": {
                                        "value": {
                                            "name": "Nome original da imagem.",
                                            "size": "Retorna o tamanho da imagem."
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "tags": ["Image"],
                "summary": "Deleta a imagem do banco.",
                "description": "Deleta a imagem no banco em relação ao Id da conta logada que vem do token.",
                "responses": {
                    "404":{
                        "description": "Falha ao deletar a imagem."
                    },
                    "200": {
                        "description": "Sucesso ao deletar imagem.",
                        "content": {
                            "application/json": {
                                "examples":{
                                    "deleteImage": {
                                        "value": {
                                            "message": "Retorna a mensagem de sucesso ao deletar a imagem."
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                
            }
        },

        "/statement": {
            "get": {
                "tags": ["Statement"],
                "summary": "Busca o estrato da conta.",
                "description": "Busca o estrato da conta e realiza essa busca com o token recebido no Headers.",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "404":{
                        "description": "Falha ao resgatar o estrato."
                    },
                    "200": {
                        "description": "Sucesso recuperar o estrato.",
                        "content": {
                            "application/json": {
                                "examples":{
                                    "statement": {
                                        "value": {
                                            "amount": "Retorna o valor da transação.",
                                            "type": "Retorna o tipo da transação.",
                                            "created_at": "Retorna a data de criação."
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },

        "/statementByDate": {
            "get": {
                "summary": "Busca o estrato por data de uma conta única.",
                "description": "Busca o estrato por data de uma conta única, que no caso seria o Id recebido do token no Headers.",
                "tags": ["Statement"],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                    "name": "startDate",
                        "in": "query",
                        "description": "Data inicial para buscar o estrato no fomato americano 'Ano - Mês - Dia'."
                    },
                    {
                        "name": "endDate",
                        "in": "query",
                        "description": "Data final para buscar o estrato no fomato americano '1001 - 01 - 01'."
                    }
                ],
                "responses": {
                    "400": {
                        "description": "Estrato não encontrado."
                    },
                    "201": {
                        "description": "Sucesso ao recuperar estrato por data.",
                        "content": {
                            "application/json": {
                                "examples":{
                                    "statementByDate": {
                                        "value": {
                                            "amount": "Retorna o valor da transação",
                                            "type": "Retorna o tipo da transação",
                                            "created_at": "Retorna a data de criação"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },

        "/statement/list": {
            "get": {
                "tags": ["Statement"],
                "description": "Busca o estrato de todas as contas.",
                "summary": "Busca o estrato de todas as contas.",
                "security":[
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "400": {
                        "description": "Falha ao resgatar os estratos."
                    },
                    "201": {
                        "description": "Sucesso ao recuperar todos os estratos.",
                        "content": {
                            "application/json": {
                                "examples":{
                                    "statementAll": {
                                        "value": {
                                            "accountId": "Retorna o Id de Account de statement",
                                            "amount": "Retorna o value da transação",
                                            "type": "Retorna o type da transação",
                                            "created_at": "Retorna a data de criação"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },

        "/deposit": {
            "post": {
                "tags": ["Transaction"],
                "summary": "Realiza o depósito na conta.",
                "description": "Realiza o depósito na conta, que no caso é o Id da conta que vem no token recebido no Headers",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Deposit"
                            },
                            "examples": {
                                "account": {
                                    "value": {
                                        "deposit": 300 
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "404":{
                        "description": "Falha ao realizar seu deposito."
                    },
                    "200": {
                        "description": "Sucesso ao depositar.",
                        "content": {
                            "application/json": {
                                "examples":{
                                    "deposit": {
                                        "value": {
                                            "name": "Retorna o name da conta depositada.",
                                            "Saldo": "Retorna o saldo da total conta depositada."
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },

        "/withdraw": {
            "post": {
                "tags": ["Transaction"],
                "summary": "Realiza o saque na conta.",
                "description": "Realiza o saque na conta referente ao Id recebido no token de verificação vindo do Headers.",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/WithDraw"
                            },
                            "examples": {
                                "account": {
                                    "value": {
                                        "withDraw": 300 
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "404":{
                        "description": "Falha ao realizar seu saque."
                    },
                    "200": {
                        "description": "Sucesso ao realizar seu saque.",
                        "content": {
                            "application/json": {
                                "examples":{
                                    "withdraw": {
                                        "value": {
                                            "name": "Retorna o name da conta.",
                                            "saque": "Retorna a quantidade do saque.",
                                            "saldo": "Retorna o saldo total da conta após o saque."
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },

        "/p2p": {
            "post": {
                "tags": ["Transaction"],
                "summary": "Realiza a transação.",
                "description": "Realiza a transação de uma conta para outra, subtraindo o saldo na conta de envio e adicionando no saldo da conta que recebe, para realizar a transferência é preciso o token no Headers, que será quem envia, e o CPF no corpo da requisição que será quem vai receber a transferência.",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/P2P"
                            },
                            "examples": {
                                "P2P": {
                                    "value": {
                                        "cpfReciever": 33342333333,
                                        "amount": 200
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "404":{
                        "description": "Falha ao realizar a transação."
                    },
                    "200": {
                        "description": "Sucesso na transferência.",
                        "content": {
                            "application/json": {
                                "examples":{
                                    "P2P": {
                                        "value": {
                                            "accountSend": "Nome da conta que está realizando a transferência.",
                                            "cashout": "Valor que está saindo da conta de 'accountSend'.",
                                            "saldo": "Saldo da conta do enviador após a transação.",
                                            "accountReciever": "Nome da conta que está recebendo a transferência.",
                                            "cashin": "Valor que está entrando na conta do 'accountReciever'."
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Account": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "cpf": {
                        "type": "number"
                    },
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    },
                    "endereco": {
                        "rua": {
                            "type":"string"
                        },
                        "bairro":{
                            "type":"string"
                        },
                        "numero": {
                            "type":"number"
                        }   
                    },
                    "telefone":{
                        "type": "number"
                    },
                    "admin": {
                        "type": "boolean"
                    }
                }
            },
            "Retrieve": {
                "type": "object",
                "properties": {
                    "cpf": {
                        "type": "number"
                    }
                }
            },
            "Deposit": {
                "type": "object",
                "properties": {
                    "deposit": {
                        "type": "number"
                    } 
                }
            },
            "WithDraw": {
                "type": "object",
                "properties": {
                    "withdraw": {
                        "type": "number"
                    } 
                }
            },
            "Password": {
                "type": "object",
                "properties": {
                    "passwordOld": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "passwordNew": {
                        "type": "string"
                    }
                }
            },
            "P2P": {
                "type": "object",
                "properties": {
                    "cpfReciever": {
                        "type": "number"
                    },
                    "amount": {
                        "type": "number"
                    }
                }
            },
            "Login": {
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    }
                }
            }
        },
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    }   
}
